services:
  # 1. Django API Backend
  - type: web
    name: modeldoctor-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: POSTGRES_DB
        value: modeldoctor
      - key: POSTGRES_USER
        value: mahi_store_db_user
      - key: POSTGRES_PASSWORD
        value: KPvK339bVwiahgbt8KEGgJHHEOzgsImV
      - key: POSTGRES_HOST
        value: dpg-d97rcgu7r5hc73d9p2v0-a.singapore-postgres.render.com
      - key: POSTGRES_PORT
        value: "5432"
      - key: CELERY_TASK_ALWAYS_EAGER
        value: "True"
      - key: CELERY_TASK_EAGER_PROPAGATES
        value: "True"
      - key: REDIS_URL
        fromService:
          type: redis
          name: modeldoctor-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: modeldoctor-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: modeldoctor-redis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: modeldoctor-frontend
          envVarKey: RENDER_EXTERNAL_URL
    dockerCommand: sh start.sh


  # 3. React Frontend Static Site
  - type: web
    name: modeldoctor-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: modeldoctor-backend
          envVarKey: RENDER_EXTERNAL_URL

  # 5. Redis Cache / Broker
  - type: keyvalue
    name: modeldoctor-redis
    plan: free
    ipAllowList: [] # only allow internal connections


