# Generated by Django 4.2.30 on 2026-07-09 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_file', models.FileField(upload_to='models/')),
                ('dataset_file', models.FileField(upload_to='datasets/')),
                ('target_column', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('results', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeakageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('drop_pct', models.FloatField()),
                ('shap_ratio', models.FloatField()),
                ('known_flag', models.BooleanField(default=False)),
                ('risk_score', models.FloatField()),
                ('audit_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leakage_results', to='audits.auditjob')),
            ],
            options={
                'ordering': ['-risk_score'],
                'unique_together': {('audit_job', 'feature_name')},
            },
        ),
        migrations.CreateModel(
            name='FeatureMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('known_at_prediction_time', models.BooleanField(default=True)),
                ('audit_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='audits.auditjob')),
            ],
            options={
                'unique_together': {('audit_job', 'feature_name')},
            },
        ),
    ]
